config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :admins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :sites do
    resources :images, :only => [:create, :destroy]
  end

  resources :blogposts

  resources :jobs

  resources :contacts

  get 'tags/:tag', to: 'sites#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  validates :blog_title, 	:presence => true
  validates :body,			:presence => true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :job_title,		:presence => true
  validates :company_name,	:presence => true
  validates :description,	:presence => true
  validates :requirement,	:presence => true
  validates :email,			:presence => true

end

app/models/site.rb
class Site < ApplicationRecord
  acts_as_taggable
  validates :site_name,		:presence => true
  validates :description,	:presence => true
  mount_uploaders :images, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:github]

  has_many :sites

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  # before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @blogposts = Blogpost.all
  end

  def show
    @blogpost = Blogpost.find(params[:id])
  end

  def new
    @blogpost = Blogpost.new
  end

  def create
    @blogpost = Blogpost.new(blogpost_params)
    if @blogpost.save
      flash[:notice] = "Blog Post added successfully"
      redirect_to blogposts_path
    else
      flash[:alert] = "Blog Post was not added"
      render :new
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update(blogpost_params)
      flash[:notice] = "Blog Post updated successfully"
      redirect_to blogpost_path(@blogpost)
    else
      flash[:alert] = "Blog Post was not updated"
      render :edit
    end
  end

  def destroy
    @blogpost = Blogpost.find(params[:id])
    @blogpost.destroy
    flash[:notice] = "Blogpost deleted"
    redirect_to blogposts_path
  end

  private
  def blogpost_params
    params.require(:blogpost).permit(:blog_title, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_site

  def create
    add_more_images(images_params[:images])
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  private

  def set_site
    @site = Site.find(params[:site_id])
  end

  def add_more_images(new_images)
    @images = @site.images
    @images += new_images
    @site.images = @images
  end

  def remove_image_at_index(index)
    remaining_images = @site.images
    delete_image = remaining_images.delete_at(index)
    delete_image.try(:remove!)
    @site.images = remaining_images
  end

  def images_params
    params.require(:site).permit({images: []})
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:job_title, :company_name, :description, :requirement, :email)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  # before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = current_user.sites.new
  end

  def create
    @site = current_user.sites.new(site_params)
    if @site.save
      redirect_to sites_path
    else
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to sites_path
    else
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:site_name, :description, :tag_list, {images: []}, {images_cache: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/github_users_helper.rb
module GithubUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/blogposts/_form.html.erb
<%= render "layouts/errors", :object => @blogpost %>

<%= form_for @blogpost do |f| %>
	<div class="form-group">
		<%= f.label :blog_title %>	
		<%= f.text_field :blog_title %>
	</div>
	
	<div class="form-group">
		<%= f.label :body %>	
	</div>
	<div class="form-group">
		<%= f.text_area :body, size: "150x20" %>
	</div>

	<%= f.submit %>
<% end %>

app/views/blogposts/edit.html.erb
<% content_for(:title, "Edit your Blog Entry | ReVamp") %>

<div class="container">
	<div class="forms">
		<h2>Edit Blog Entry</h2>
		<hr>
		<%= render "form" %>
	</div>
</div>

app/views/blogposts/index.html.erb
<% content_for(:title, "Blog Posts | ReVamp") %>

<div class="container">
  <div class="blog-head">
    <h2>How - To Blogs</h2>
  </div>
  <hr>
      <% if @blogposts.any? %>
        <ul>
          <div class="row">
            <% @blogposts.each do |blogpost| %>
            <div class="col-md-5 blog-body-truncated">
              <li><%= link_to blogpost.blog_title, blogpost_path(blogpost), {class: "blog-title"} %> <br>
                  <%= truncate(blogpost.body, :length => 100) %><%= link_to " Read more", blogpost_path(blogpost) %></li>
              </div>
            <% end %>
            </div>
          </ul> 
        <% else %>
          <center><p>No blog has been added yet</p></center>
        <% end %>
  <% if user_signed_in? %>
    <%= link_to "Add A Blogpost", new_blogpost_path %>
  <% end %>
</div>

app/views/blogposts/new.html.erb
<% content_for(:title, "Add A Blog Entry | ReVamp") %>

<div class="container">
  <div class="forms">
    <h2>New Blog Post</h2>
   	<hr>
    <%= render "form" %>
   </div>
</div>

app/views/blogposts/show.html.erb
<% content_for(:title, "Blog | ReVamp") %>

<div class="container">
    <div class="blog-body">
        <div class="blog-head">
            <h2><%= @blogpost.blog_title %></h2>
        </div>
        <hr>
        <p><%= @blogpost.body %></p>
        <% if user_signed_in? %>
        <p><%= link_to "Edit Blog Post", edit_blogpost_path %> | <%= link_to "Delete Blog Post", blogpost_path(@blogpost), :data => { :confirm => "Are you sure you want to delete this Blog Post?", :method => "delete" } %></p>
        <% end %>
    </div> 
    <div id="disqus_thread"></div>
    <script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://revamp.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

app/views/jobs/_form.html.erb
<%= render "layouts/errors", :object => @job %>

<div class="container" id="job_post">
<%= form_for @job do |f| %>
	<div class="form-group">
		<%= f.label :job_title %>	
		<%= f.text_field :job_title %>
	</div>
	<div class="form-group">
		<%= f.label :company_name %>	
		<%= f.text_field :company_name %>
	</div>
	
	<div class="form-group">
		<%= f.label :description %>	
	</div>
	<div class="form-group">
		<%= f.text_area :description, size: "40x6" %>
	</div>
	
	<div class="form-group">
		<%= f.label :requirements %>	
	</div>
	<div class="form-group">
		<%= f.text_area :requirement, size: "40x6" %>
	</div>

	<div class="form-group">
		<%= f.label :email %>	
		<%= f.text_field :email %>
	</div>

	<%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<% content_for(:title, "Edit Job Vacancy | ReVamp") %>

<div class="container">
	<div class="forms">
		<h2>Edit Job Entry</h2>
		<hr>
		<%= render "form" %>
	</div>
</div>

app/views/jobs/index.html.erb
<% content_for(:title, "Job Board | ReVamp") %>

<div class="container">
  <div class="jobs_head">
    <h2>Jobs</h2>
  </div>
  <hr>
  <div class="jobs_body">
    <% if @jobs.any? %>
      <ul>
        <% @jobs.each do |job| %>
          <li><%= link_to job.job_title, job_path(job), class: "job-header" %> <br>
          <%= truncate(job.description, :length => 100) %><%= link_to "Read more", job_path(job) %></li> <hr>
        <% end %>
      </ul>	
    <% else %>
      <center><p>No jobs have been advertised yet</p></center>
    <% end %> <br>
  <hr>
    <%= link_to "Add A Job", new_job_path %>
  </div>
</div>

app/views/jobs/new.html.erb
<% content_for(:title, "Add a Job Vacancy | ReVamp") %>

<div class="container">
	<div class="forms">
		<h2>New Job Post</h2>
		<hr>
		<%= render "form" %>
	</div>
</div>

app/views/jobs/show.html.erb
<% content_for(:title, "Job Vacancy | ReVamp") %>

<div class="container-fluid">
	<h2><%= @job.job_title %></h2>
	<h4>By: <%= @job.company_name %></h4>
	<hr>
	<h3>Description</h3>
	<p><%= @job.description %></p>
	<h3>Requirements</h3>
	<p><%= @job.requirement %></p>
	<p>Send your CVs to <%= @job.email %></p>

	<p><%= link_to "Edit Job Post", edit_job_path %> | <%= link_to "Delete Job Post", job_path(@job), :data => { :confirm => "Are you sure you want to delete this Job Post?", :method => "delete" } %></p>
</div>