config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :admins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :sites do
    resources :images, :only => [:create, :destroy]
  end

  resources :blogposts

  resources :jobs

  resources :contacts

  get 'tags/:tag', to: 'sites#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  validates :blog_title, 	:presence => true
  validates :body,			:presence => true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :job_title,		:presence => true
  validates :company_name,	:presence => true
  validates :description,	:presence => true
  validates :requirement,	:presence => true
  validates :email,			:presence => true

end

app/models/site.rb
class Site < ApplicationRecord
  acts_as_taggable
  validates :site_name,		:presence => true
  validates :description,	:presence => true
  mount_uploaders :images, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:github]

  has_many :sites

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  # before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @blogposts = Blogpost.all
  end

  def show
    @blogpost = Blogpost.find(params[:id])
  end

  def new
    @blogpost = Blogpost.new
  end

  def create
    @blogpost = Blogpost.new(blogpost_params)
    if @blogpost.save
      flash[:notice] = "Blog Post added successfully"
      redirect_to blogposts_path
    else
      flash[:alert] = "Blog Post was not added"
      render :new
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update(blogpost_params)
      flash[:notice] = "Blog Post updated successfully"
      redirect_to blogpost_path(@blogpost)
    else
      flash[:alert] = "Blog Post was not updated"
      render :edit
    end
  end

  def destroy
    @blogpost = Blogpost.find(params[:id])
    @blogpost.destroy
    flash[:notice] = "Blogpost deleted"
    redirect_to blogposts_path
  end

  private
  def blogpost_params
    params.require(:blogpost).permit(:blog_title, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_site

  def create
    add_more_images(images_params[:images])
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  private

  def set_site
    @site = Site.find(params[:site_id])
  end

  def add_more_images(new_images)
    @images = @site.images
    @images += new_images
    @site.images = @images
  end

  def remove_image_at_index(index)
    remaining_images = @site.images
    delete_image = remaining_images.delete_at(index)
    delete_image.try(:remove!)
    @site.images = remaining_images
  end

  def images_params
    params.require(:site).permit({images: []})
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:job_title, :company_name, :description, :requirement, :email)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  # before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = current_user.sites.new
  end

  def create
    @site = current_user.sites.new(site_params)
    if @site.save
      redirect_to sites_path
    else
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to sites_path
    else
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:site_name, :description, :tag_list, {images: []}, {images_cache: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/github_user_sessions_helper.rb
module GithubUserSessionsHelper
end

app/helpers/github_users_helper.rb
module GithubUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= render "layouts/errors", :object => @site %>

<%= form_for @site, html: { multipart: true } do |f| %>
	<div class="form-group">
		<%= f.label :site_name %>
		<%= f.text_field :site_name %>
	</div> <br>
	<div class="form-group">
		<%= f.label :description , "Link to Original Site" %>
		<%= f.text_field :description %>
	</div> <br>
	<div class='form-group'>
    	<%= f.label :tag_list, 'Tags (separated by commas)' %><br/>
    	<%= f.text_field :tag_list %>
	</div> <br>
	<div class='form-group'>
    	<%= f.label :images %>
		<%= f.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png" %>
		<%= f.hidden_field :images_cache %>
		
		<% if @site.images?%>
			<% @site.images.each do |image| %>
		 		<%= image_tag image.url.to_s %>
			<% end %>
		<% end %>

	</div>
	<%= f.submit %>
<% end %>

app/views/sites/edit.html.erb
<% content_for(:title, "Edit Your Revamped site | ReVamp") %>

<div class="container">
	<div class="forms">
		<h2>Edit Site Details</h2>
		<hr>
		<%= render "form" %>
	</div>
</div>

app/views/sites/index.html.erb
<% content_for(:title, "Revamped Sites | ReVamp") %>

<div class="container">
  <div class="sites-head">
    <h1>Sites</h1>
  </div>
  <hr>
  <div class="sites-body">
    <% if @sites.any? %>
      <ul>
          <div class="row">
        <% @sites.each do |site|%>
            <div class="col-md-3 site-index" style="background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url(<%= site.images[0] %>);
            background-size: cover;"> 
              <li><%= link_to site.site_name, site_path(site) %></li>     
            </div>
        <% end %>
            </div>
      </ul>
    <% else %>
      <p>There are no sites yet!</p>
    <% end %>
  </div>
          <% if user_signed_in? %>

  <%= link_to "Add New Site", new_site_path %>
  <% end %>
  <hr>
  <div id='tag_cloud'>
  <h2>Categories</h2>
    <% tag_cloud Site.tag_counts, %w{s m l} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

app/views/sites/new.html.erb
<% content_for(:title, "Upload Your Revamped site | ReVamp") %>

<div class="container">
  <div class="forms">
    <h2>Add A Site</h2>
    <hr>
    <%= render "form" %>
  </div>
</div>

app/views/sites/show.html.erb
<% content_for(:title, "Site | ReVamp") %>

<div class="container">
  <div class="sites-head">
    <h2><%= @site.site_name %></h2>
  </div>
  <div class="sites-body">
    <%= link_to @site.description, @site.description, target: '_blank' %>

    <% @site.images.each_with_index do |image, index| %>
      <%= image_tag image.url.to_s, {class: "site-screenshots"} %>
    <% if user_signed_in? %>
      <%= link_to "Delete", site_image_path(@site, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
        <% end %>
    <% end %>

  <div class="add-images">
    <% if user_signed_in? %>
      <h4>Add More Images</h4>
      <%= form_for @site, url: site_images_path(@site), method: :post do |f| %>
        <%= f.file_field :images, multiple: true %>
        <%= f.submit %>
      <% end %>
    <% end %>
    </div>
    <hr>

    <p>Tags: <%= raw(@site.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>

    <hr>
        <% if user_signed_in? %>

    <p><%= link_to "Edit Site", edit_site_path %> | <%= link_to "Delete Site", site_path(@site), :data => { :confirm => "Are you sure you want to delete this Site?", :method => "delete" } %></p>
        <% end %>

    </div> <br> <br>
    <div id="disqus_thread"></div>
      <script>
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://revamp.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>