config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :admins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :sites do
    resources :images, :only => [:create, :destroy]
  end

  resources :blogposts

  resources :jobs

  resources :contacts

  get 'tags/:tag', to: 'sites#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  validates :blog_title, 	:presence => true
  validates :body,			:presence => true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :job_title,		:presence => true
  validates :company_name,	:presence => true
  validates :description,	:presence => true
  validates :requirement,	:presence => true
  validates :email,			:presence => true

end

app/models/site.rb
class Site < ApplicationRecord
  acts_as_taggable
  validates :site_name,		:presence => true
  validates :description,	:presence => true
  mount_uploaders :images, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:github]

  has_many :sites

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_site

  def create
    add_more_images(images_params[:images])
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    if @site.save
      redirect_to sites_path
    else
      redirect_to :back
    end
  end

  private

  def set_site
    @site = Site.find(params[:site_id])
  end

  def add_more_images(new_images)
    @images = @site.images
    @images += new_images
    @site.images = @images
  end

  def remove_image_at_index(index)
    remaining_images = @site.images
    delete_image = remaining_images.delete_at(index)
    delete_image.try(:remove!)
    @site.images = remaining_images
  end

  def images_params
    params.require(:site).permit({images: []})
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:job_title, :company_name, :description, :requirement, :email)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  # before_action :authenticate_admin!, :except => [:index, :show]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = current_user.sites.new
  end

  def create
    @site = current_user.sites.new(site_params)
    if @site.save
      redirect_to sites_path
    else
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to sites_path
    else
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:site_name, :description, :tag_list, {images: []}, {images_cache: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/github_users_helper.rb
module GithubUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
	<h3>There are some errors that need to be fixed</h3>
	<ul>
		<% object.errors.full_message.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Arvo|Montserrat|Rubik|Source+Sans+Pro" rel="stylesheet">
	<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    
  <body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="/" class="navbar-brand">ReVamp</a>

			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><%= link_to 'Home', root_path  %></li>
					<li><%= link_to 'Sites', sites_path  %></li>
					<li><%= link_to 'Blogs', blogposts_path  %></li>
					<li><a href="#contacts-body">Contacts</a></li>					
					<li class="dropdown">
						<% if user_signed_in? %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Edit profile', edit_user_registration_path %></li>
								<li><%= link_to 'Logout ', destroy_user_session_path, :method => :delete %></li> 
							</ul>   
						<% else %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Join The Community<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to 'Sign Up ', new_user_registration_path  %></li>
								<li><%= link_to 'Login ', new_user_session_path  %></li>  
							</ul>
						<% end %>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>  
	<div class="content">
		<%= yield %>
	</div>
	<div id="contacts-body">
		<div class="container">
		<div class="contacts-head">
		<h2>Contact Us</h2>
		</div>
		<hr>
			<p><span class="glyphicon glyphicon-envelope"></span> EMAIL: revamp@gmail.com</p>
			<p><span class="ion-android-call"></span> CALL: +254 732 716 187</p>
		<a href="http://twitter.com/" class="icon-button twitter"><i class="ion-social-twitter"></i><span></span></a>
		<a href="http://facebook.com" class="icon-button facebook"><i class="ion-social-facebook"></i><span></span></a>
		<a href="http://plus.google.com" class="icon-button google-plus"><i class="ion-social-googleplus"></i><span></span></a>
		</div>
	</div>
	<div id="footer">
		<div class="container">
			<h5> &#169 ReVamp <%= Time.current.year %></h5>
		</div>
	</div>	
  </body>
  
</html>